### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by eeeman1** [ealush/emoji-picker-react#147] opened 2020-05-19 12:43 UTC
document is not defined

const [chosenEmoji, setChosenEmoji] = useState(null);
    const [mounted, setMounted] = useState(null);

    useEffect(() => setMounted(true), []);

.......

                            {mounted &&

                                <Fragment>

                                    <Picker onEmojiClick={(event, emojiObject) => {
                                        setChosenEmoji(emojiObject);
                                    }}/>

                                    {chosenEmoji.emoji}

                                </Fragment>

                            }

**Comment by ealush** [comment] 2020-05-19 15:06
Hey @eeeman1, your example is not sufficient for me to reproduce what you're describing. See this: https://stackblitz.com/edit/emoji-picker-react-gv9idx?file=index.js

Can you try to create a new blitz that reproduces your bug?

**Comment by gasscoelho** [comment] 2020-09-13 04:52
@eeeman1 are you using some SSR like Next.js or something like that? I believe the V3 doesn't support SSR. I'm having a problem with `document is not defined` too, but that's because Node.js doesn't have access to the DOM API as `document` for example. So every time your app renders though the backend you'll get this error.

P.S. If you are not using any SSR then ignore this comment 😅

**Comment by ealush** [comment] 2020-09-21 21:37
@gasscoelho hey, in general, no, the picker does not support ssr - and I believe it also shouldn't for multiple reasons.

The technical reason it doesn't support ssr is due to the way css is handled. If you really need ssr support, you could probably grab the files directly from source, and configure transpiling of that module as well.

I would recommend, though, unless you really need the picker visible on initial load not to render it on the server, but instead show it later, or even better - dynamically import it later on. It is a pretty heavy component with lots of assets, and thousands of elements. It also runs a pretty intense mapping of search keywords right at start.

**Comment by archywillhe** [comment] 2020-10-09 22:47
yeah getting this cuz of ssr. To turn of ssr use `dynmaic~`

```
import dynamic from "next/dynamic";
const NoSSRComponent = dynamic(() => import("../components/NoSSRComponent"), {
  ssr: false,
});
```

**Comment by matheusslg** [comment] 2021-07-21 18:50
https://github.com/ealush/emoji-picker-react/issues/184#issuecomment-884411920

**Comment by Chukstart** [comment] 2021-08-06 21:50
> yeah getting this cuz of ssr. To turn of ssr use `dynmaic~`
> 
> ```
> import dynamic from "next/dynamic";
> const NoSSRComponent = dynamic(() => import("../components/NoSSRComponent"), {
>   ssr: false,
> });
> ```

Could you send an example component and utilization the entire shebang

**Comment by Chukstart** [comment] 2021-08-06 21:54
> yeah getting this cuz of ssr. To turn of ssr use `dynmaic~`
> 
> ```
> import dynamic from "next/dynamic";
> const NoSSRComponent = dynamic(() => import("../components/NoSSRComponent"), {
>   ssr: false,
> });
> ```

Great this works

**Comment by Riaz5687** [comment] 2021-11-23 14:42
use dynamic import in nextjs it just because of serverside rendering

**Comment by ealush** [comment] 2021-12-11 23:15
closing as duplicate of #184

**Closed by ealush** 2021-12-11 23:15 UTC
Labels: duplicate
