### ISSUE TITLE
Relaxed emoji is not handled right

### ISSUE THREAD

**Issue by kodai3** [ealush/emoji-picker-react#198] opened 2021-07-05 05:06 UTC
It's reproducible with live demo on Chrome, but not on Safari 🤔
https://stackblitz.com/edit/emoji-picker-react?file=index.js

Chrome: relaxed emoji
![image](https://user-images.githubusercontent.com/33568829/124420018-a309df00-dd99-11eb-9cf0-74e9d3fffe1d.png)

Chrome: kissing emoji
![image](https://user-images.githubusercontent.com/33568829/124420051-b452eb80-dd99-11eb-9fec-8c13f9a45b06.png)

Safari: relaxed emoji
![image](https://user-images.githubusercontent.com/33568829/124429682-20891b80-dda9-11eb-8d18-b25202a94117.png)

**Comment by kodai3** [comment] 2021-08-21 12:03
https://github.com/googlefonts/noto-emoji/issues/90#issuecomment-541381574

**Comment by kodai3** [comment] 2021-08-21 12:17
https://stackoverflow.com/questions/54772829/smiling-face-relaxed-emoji-not-displaying-in-html

**Comment by ealush** [comment] 2021-12-11 23:14
Thank you, and I am extremely sorry for taking this long. I will release a fix in the upcoming patch version.

**Comment by ealush** [comment] 2021-12-11 23:50
Fixed in 3.4.11

**Closed by ealush** 2021-12-11 23:50 UTC
Labels: bug

**Comment by kodai3** [comment] 2021-12-13 00:53
Thank you for the fix 🎉

**Comment by albertodeavila** [comment] 2021-12-15 09:08
Thanks @ealush! It's been fixed on the emoji picker, but it's not working fine when you try to render it it.
![image](https://user-images.githubusercontent.com/9431295/146156759-0f9261db-1ef8-4c9b-89c7-8cef99ca8cc7.png)

Thanks for the great job with this :)

**Comment by ealush** [comment] 2021-12-15 09:53
@albertodeavila see the stackoverflow link that @kodai3 linked to. You're going to need to use the correct font family to render the emoji.

https://stackoverflow.com/a/56711140

**Comment by albertodeavila** [comment] 2021-12-15 11:49
Yup, I've read it, but why can't the library return the icon as it's suggested [here](https://stackoverflow.com/a/54773116)? 
Again, thanks for work and the quickly response 😄

**Comment by ealush** [comment] 2021-12-15 12:49
Hey @albertodeavila :)
There are two things at play here
1. in terms of providing specific support for one or another emoji - I don't curate the emojis myself, instead I use a third party library called [emoji-datasource](https://www.npmjs.com/package/emoji-datasource).
2. I believe the unified provided by the picker is actually the correct one, so I'm going to have to look whether this is an issue with the datasource, or maybe that stackoverflow answer isn't accurate. It could also be a bug in the picker itself where it some of the unified code removed, but I did not find evidence for it in the code.

![image](https://user-images.githubusercontent.com/11255103/146189285-71bd1b99-55dc-4842-aca1-56ec44680acb.png)

**Comment by CalvinJamesHeath** [comment] 2024-01-15 17:04
The issue is with Chrome as it works fine in Safari.
