### ISSUE TITLE
Search is extremely laggy

### ISSUE THREAD

**Issue by amitava82** [ealush/emoji-picker-react#133] opened 2019-12-13 03:00 UTC
Title. I've tried the demo and it takes a second or more on each keystroke to update UI.

**Comment by ealush** [comment] 2019-12-18 22:20
Hey, @amitava82 .
Weird, I can't replicate - but I have a theory. I believe that the search results show up immediately, but their images take more time to load since they were not preloaded. Does that seem like the case?

It would look somewhat like this:
The search results actually do take up space (you see that the food & drink category is showing and has a height) but not all images loaded yet - even though they are hoverable.

![image](https://user-images.githubusercontent.com/11255103/71128020-fd157480-21f4-11ea-9752-e21adfce627e.png)

If that's the case, I would recommend trying to preload all emojis so that won't happen on slow connections:
`<Picker onEmojiClick={onEmojiClick} preload/>`

**Comment by amitava82** [comment] 2019-12-19 02:15
No, it is not that. It is the keystroke that is laggy. On each keystroke it takes couple of seconds to update input because some reason thread is being blocked.

**Comment by hugomallet** [comment] 2020-05-20 12:10
This module suffers of (extremly) poor performance because memoization issue. One possible fix : 

First wrap the component into a memoized component  : 
```js
const MemoEmojiPicker = React.memo(EmojiPicker);
```

Then use it like this : 

```js
// ...
const handleEmojiClickRef = useRef();
const handleEmojiClickFix = useCallback((...args) => handleEmojiClickRef.current(...args), []);
useEffect(() => { handleEmojiClickRef.current = handleEmojiClick; });

return (
    // ...
    <MemoEmojiPicker onEmojiClick={handleEmojiClickFix} />
    // ...
);
```

Hope this helps

**Comment by ealush** [comment] 2020-05-20 16:54
Hey, @hugomallet. Unfortunately I don't think it is that simple. After many spending quite a while investigating the render and performance issue I can confidently say that it is not related to memoization, but to the sheer amount of elements to render at once.

What would probably help solving this would be some kind of a virtualized list - a feature I am planning to add sometime in the future.

**Comment by ealush** [comment] 2020-06-01 21:38
In 3.2 I touched a little on performance. Nothing huge, but it should slightly improve initial load time and also the full render after clearing the search term - these are the two main bottlenecks.

I will working on perf in a later version.

**Comment by amitava82** [comment] 2020-06-02 01:43
The demo app throws error after typing few characters.
Error in /turbo_modules/emoji-picker-react@3.2.0/dist/index.js (2:155784)
Cannot read property 'length' of undefined

**Comment by ealush** [comment] 2020-06-02 05:51
Thanks, looking into it.

**Comment by ealush** [comment] 2020-08-29 23:12
@internationalhouseofdonald Hey, I believe that memoization won't help much here - in our case the problem is related to the sheer amount of elements we render at once.

**Comment by codecracker05** [comment] 2022-01-19 07:01
am getting an error while click on the icon. it takes more time to load
![Screenshot 2022-01-10 at 5 46 08 PM](https://user-images.githubusercontent.com/96469935/150080370-222933e3-92ba-4c04-90a6-a042e1d28245.png)

**Comment by Geczy** [comment] 2022-07-13 21:46
the whole package slows down performance of my site for every react update i make

**Comment by ealush** [comment] 2022-07-29 21:13
> # Suggestion
> To improve performance, instead of loading all the images from the cdn, can't the images be included with the package? @ealush
> 
> so we don't have to download all images on render but on install
> 
> I think its better to waste time on install than for all the user to have to suffer a laggy component

See my reply here: https://github.com/ealush/emoji-picker-react/issues/224#issuecomment-1054241800

To summarize - including the images as part of the package, would put the burden on you to find a decent way to store and serve the 1600+ image files, because simply having them in your node modules directory is obviously not enough.

Alternatively, if you're into serving the emojis from your own cdn rather the one publicly available, you can actually do that, and provide your own cdn url.

**Comment by jeffometer** [comment] 2022-08-16 14:25
Maybe I am missing something, but would a sprite sheet help (hosted on the public cdn)?  That cuts down the request count and it can be preloaded/cached similar to html5 games.  The preload option doesn't seem to work for me either as is.

**Comment by ealush** [comment] 2022-08-16 14:37
> Maybe I am missing something, but would a sprite sheet help (hosted on the public cdn)? That cuts down the request count and it can be preloaded/cached similar to html5 games. The preload option doesn't seem to work for me either as is.

That's actually something I've tried before, but at least back then, the publicly available sprite wasn't good enough due to both low-res and subpixle positioning.
https://github.com/ealush/emoji-picker-react/issues/224#issuecomment-1199947330

Along with that, the sprite is not ordered per-category, which means that until the whole sprite loads, categories would be partially visible.

I also believe that the lagginess in search is not due to the image loading - but mostly due to re-rendering of so many elements.

Regardless of all that, I am willing to accept a PR adding support for the sprite, if we see that it actually improves the performance of the picker.

**Comment by jeffometer** [comment] 2022-08-16 14:44
> Along with that, the sprite is not ordered per-category, which means that until the whole sprite loads, categories would be partially visible.

I was intending/hoping to load the full sheet near page load/component init, rather than picker open.

I won't be able to get to a PR atm, but I'll keep an eye on this.  In the meantime I switched to native which seems to work way better, especially in searches.  Is there a drawback to using native mode?

thanks!

**Comment by ealush** [comment] 2022-08-16 14:56
Preloading all images is actually something we can do as a quick optimization regardless of the sprite. Might be worth exploring this too.

Native is indeed snappier, and looks better too. The main drawback would be that it looks different on every OS, and older OS's may miss some of the emojis. If that's not an issue for you, then you should be fine.

**Comment by Geczy** [comment] 2022-08-16 16:36
you don't ahve to use sprite maps. you can load each image per unicode, like /64/<unicode>.png

**Comment by ealush** [comment] 2022-08-16 16:47
> you don't ahve to use sprite maps. you can load each image per unicode, like `/64/<unicode>.png`
> 
> 

That's how it works now

**Comment by ealush** [comment] 2022-09-02 12:43
Interested to learn: I've recently (in the past few weeks) been working on a fourth major version of the picker. It is a complete re-write, and as such I've tried to tackle the performance issues the current version has, along with adding some new features.

Would love to hear what you think about the usability of this new version, here you can try out its pre-release:

https://codesandbox.io/s/floral-rgb-z2gkzp?file=/src/App.tsx

**Comment by ealush** [comment] 2022-09-25 21:55
Since v4 is out now, I hope it handles most cases. It definitely does not handle the loading speed of emoji images, but this has nothing to do with search speed, which has been improved greatly. Closing this.

**Closed by ealush** 2022-09-25 21:55 UTC
